name: dsm2-calsim-analysis
channels:
  - conda-forge
  - cadwr-dms
  - defaults
dependencies:
  - python<3.14
  - click
  - pyyaml
  - numpy
  - netcdf4
  - pandas
  - diskcache
  - panel
  - plotly
  - pyhecdss
  - pip
  - pip:
      - kaleido
      - -e .
