output_locations: "info/DSM2_ec_loc_stds.csv"
scenarios:
  - name: "1ex_2020"
    fpath: "scenarios/1ex_2020_EC_p.dss"
  - name: "7pp_2020"
    fpath: "scenarios/7pp_2020_EC_p.dss"
variable: "EC-MEAN"
interval: "1DAY"
calsim_file: "scenarios/calsim.dss"
delta_standards:
  - name: "D1641 AG WI"
    fpath: "info/D1641_AG_wiDelta.csv"
    variable: "EC-MEAN-14DAY"
  - name: "D1641 AG South"
    fpath: "info/D1641_AG_sDelta.csv"
    variable: "EC-MEAN-30DAY"
  - name: "D1641 AG Export"
    fpath: "info/D1641_AG_export.csv"
    variable: "EC-MEAN-30DAY"
  - name: "D1641 FWS SJR"
    fpath: "info/D1641_FWS_SJR.csv"
    variable: "EC-MEAN-14DAY"
  - name: "D1641 FWS Suisun"
    fpath: "info/D1641_FWS_Suisun.csv"
    variable: "EC-MAX-MEAN"
  - name: "D1641 MI 250"
    fpath: "info/D1641_MI_250.csv"
    variable: "Chloride-MEAN"
  - name: "D1641 MI 150"
    fpath: "info/D1641_MI_150.csv"
    variable: "Chloride-MEAN"
  #- name: "D1641 FWS Suisun1"
  #  fpath: "info/D1641_FWS_Suisun1.csv"
  #  variable: "EC-HT-MEAN"
  #  interval: "1DAY"
period: 
  - "1921-01-01"
  - "2021-09-30"
plots:
  - type: "plot_step_w_regulation"
    options:
      yaxis_name: "14-day running average EC - standard (mmhos/cm)"
      title: "EC 14-Day Mean for D1641_AG West&Interior Delta Timelines"
      delta_standard: "D1641 AG WI"
  - type: "plot_exceedance_w_regulation"
    options:
      yaxis_name: "14-day running average EC - standard (mmhos/cm)"
      title: "EC 14-Day Mean for D1641_AG West&Interior Delta Exceedances"
      delta_standard: "D1641 AG WI"
